apiVersion: v1
kind: Service
metadata:
  name: student-app-api
  namespace: k8s-full-stack-example
spec:
  selector:
    app: student-app-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080