apiVersion: v1
kind: Service
metadata:
  name: student-app-client-service
  namespace: k8s-full-stack-example
spec:
  selector:
    app: student-app-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP