steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/student-app-api:$SHORT_SHA"
      - "."

  # This step pushes the image to Container Registry

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/student-app-api:$SHORT_SHA"


# docker build .